### ISSUE TITLE
not compatible with upcoming wagtail 2.7

### ISSUE THREAD

**Issue by JanMalte** [neon-jungle/wagtailmodelchooser#17]
Wagtail 2.6.3 show this warning already
`/home/maltegerth/Projects/gws-netzwerk/env/lib/python3.5/site-packages/wagtail/utils/pagination.py:10: RemovedInWagtail27Warning: wagtail.utils.pagination is deprecated. Use django.core.paginator.Paginator directly with get_page instead
  category=RemovedInWagtail27Warning)`

Using the 2.7rc2 is not working due to this startup error
`
File "/home/dev/project/env/lib/python3.5/site-packages/wagtailmodelchooser/views.py", line 8, in <module>
    from wagtail.utils.pagination import paginate
ImportError: No module named 'wagtail.utils.pagination'
`

**Comment by seb-b** [comment]
Fixed in 2.2.2
