### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by pierremanceaux** [neon-jungle/wagtailmodelchooser#22]
Hello there, and first of all, thank you for this nice model chooser, very useful 👍 .

I probably have found a bug, but I don't see where the problem could be coming from.

**Description**
When having a lot of model instances to choose from, the admin modal add a "Next" pagination link. This links works fine for me until this specific commit: https://github.com/neon-jungle/wagtailmodelchooser/commit/185cfa12db1ef60aec5dc2981a86ac6a17bb5232

When it works (any commit before this one), the request loads `http://127.0.0.1:3000/admin/chooser/[model_name]/[instance_name]/?ajax=1&p=2`

From this commit on, the request points to `http://127.0.0.1:3000/admin/pages/[page_id]/edit/?ajax=1&p=2` which has for effect to load the whole admin inside the modal, and breaks all JS event listeners in the parent page.

I don't see what could be the reason for that problem in this commit, but there must be something.

I can provide more information on demand.

Thanks a lot in advance.

**Comment by seb-b** [comment]
oh dang, I'll try to get to this shortly. In the meantime you can use version 2.2.x

**Comment by seb-b** [comment]
@pierremanceaux  I just tried this out locally and couldn't reproduce it. Is it possible you have an older version of the static files cached?

![image](https://user-images.githubusercontent.com/1635388/79415312-6dd86c00-7ff0-11ea-8c21-114eb4fbb1bd.png)

**Comment by pierremanceaux** [comment]
Thanks for the quick answer @seb-b, much appreciated!
I will play around with the static files soon to see if that can be the cause of the issue and get back to you asap. 👍

**Comment by pierremanceaux** [comment]
@seb-b I have deleted the `./static/` folder, run `./manage.py collectstatic --noinput`, clear browser cache, but problem persists. Is there anything else I could do to help?

Are you by any chance on the wagtail slack?

**Comment by pierremanceaux** [comment]
I also have tried the pagination in another modal (native page chooser) and I confirm that the problem affects only the modal from wagtailmodelchooser.

**Comment by seb-b** [comment]
@pierremanceaux Yep I'm on the slack feel free to ping me on there. If you can send through what you have installed I can try with the same versions of wagtail + django + python

**Comment by seb-b** [comment]
Thanks for the help, 2.3.2 has been release for a fix
