### ISSUE TITLE
Django Compatibility

### ISSUE THREAD

**Issue by tannerrimes12** [neon-jungle/wagtailmodelchooser#26]
Please make compatible with Django 3.1

**Comment by seb-b** [comment]
Do you have any more information on this one? I'm currently using this app on a couple of Django 3.1 projects with no problems.

**Comment by tannerrimes12** [comment]
remote: ERROR: wagtailmodelchooser 0.3.0 has requirement Django<2.2,>=1.11, but you'll have django 3.1.7 which is incompatible.

I get this when pushing to production.

**Comment by tannerrimes12** [comment]
Found the problem. I was testing different modelchoosers that are called by the same package name 'wagtailmodelchooser'. I didn't uninstall the other one before trying this one.
