### ISSUE TITLE
Access to model fields. 

### ISSUE THREAD

**Issue by vitellolabs** [neon-jungle/wagtailmodelchooser#28]
Am I correct in thinking that we can only access the string method of the selected model in templates? I am trying to access fields of that model but I can't seem to be able to do it.

**Comment by seb-b** [comment]
Would you be able to give an example of what you mean? Modelchooser templates or using your field in a page template?

Your modelchooser field should just be a foreignkey to another model, so any field on the related model will be accessible in your page template

**Comment by cam-yates** [comment]
closing this since quite some time has passed but happy to reopen with more information
