### ISSUE TITLE
'CityChooser' object has no attribute 'required_fields'

### ISSUE THREAD

**Issue by seun-otosho** [neon-jungle/wagtailmodelchooser#31]
Hi 

I'm new to this library and I am trying to use it to choose from a large list using the search
following the examples in the readme for the search I get the error

'CityChooser' object has no attribute 'required_fields'

please help

many thanks in advance

cheers

**Comment by seb-b** [comment]
Hi @seun-otosho,

What version of wagtail are you using? Is the code just a straight copy of the code from the README?

**Comment by seb-b** [comment]
also if you could attach a stack track that might help too

**Comment by seun-otosho** [comment]
I'm using the latest wagtail
also I will re-run and attach the screenshot of the stack trace

**Comment by cam-yates** [comment]
Closing since this issues getting stale but happy to reopen if someone can replicate
