### ISSUE TITLE
widget_overrides in ModelChooserPanel is deprecated with Wagtail 3

### ISSUE THREAD

**Issue by 5in4** [neon-jungle/wagtailmodelchooser#44]
The `widget_overrides` function has been replaced by `get_form_options`: https://docs.wagtail.org/en/stable/releases/3.0.html#api-changes-to-panels-edithandlers.

This is needed to get any Widget replaced with the Panel option.

Is backwards compatibility to Wagtail 2 still needed? If not, this call could just be replaced.

**Comment by seb-b** [comment]
fixed in the latest version (also no longer has a custom fieldpanel)
